services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://app:app@db:5432/appdb
      - PORT=8080
    depends_on:
      - db
    ports:
      - "8080:8080"
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
volumes:
  dbdata:
