apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # Overwrite at deploy time using --set or a separate values file with encrypted secrets (e.g., SOPS/SealedSecrets)
  DATABASE_URL: "postgresql://app:app@postgres.app.svc.cluster.local:5432/appdb"
